version: '3.8'
services:
  web:
    #container_name: "rails-4-docker-web
    platform: "linux/amd64"
    build:
      context: .
      args:
        BUNDLE_ENTERPRISE_CONTRIBSYS_COM:
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .rbenv-vars
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    extra_hosts:
        - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
  sidekiq:
    platform: "linux/amd64"
    build:
      context: .
      args:
        BUNDLE_ENTERPRISE_CONTRIBSYS_COM:
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
      - .rbenv-vars
    extra_hosts:
        - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
  testserver:
    platform: "linux/amd64"
    build:
      context: .
      args:
        BUNDLE_ENTERPRISE_CONTRIBSYS_COM:
    command: bundle exec rake test_server:run
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
      - .rbenv-vars
    extra_hosts:
        - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
volumes:
  bundle:
